name: Create and publish packages

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}/backend
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/frontend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend  # Ensure your backend Dockerfile is in the 'backend' directory
          file: ./backend/Dockerfile  # Explicitly specify the Dockerfile path
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend  # Ensure your frontend Dockerfile is in the 'frontend' directory
          file: ./frontend/Dockerfile  # Explicitly specify the Dockerfile path
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            docker pull ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            docker stop backend-app || true
            docker stop frontend-app || true
            docker rm backend-app || true
            docker rm frontend-app || true
            docker run -d --name backend-app -p 80:80 ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            docker run -d --name frontend-app -p 8080:8080 ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
